### ISSUE TITLE
No Coin No Working

### ISSUE THREAD

**Issue by TheGuardianWolf** [gunthercox/NoCoin#2]
I followed the instructions of starting the mining program with

```
 
 
```
But I'm not observing no coins being produced. Pls fix.

**Comment by gunthercox** [comment]
Have you tried the following?

```
 
```

**Comment by TheGuardianWolf** [comment]
I ran those commands and I think I see some content on my terminal, but now there seems to be another error:

```
.̶̢̢̧̡̢̨̨̧̢̡̧̨̧̨̧̛̛̛̛͍̝͓̜͇͚̞͍̹̻̺͖͙̦̭̤̘͔̜̹̯̤͇̳̦͇̹̣̟̼̗̦͕̹̰̰̝̪̬̫̖̞͓̲͕̜̗̭̣̣͓̙̺̯̭͕̪̦̦̱̺͚̰̼͔̠̙̻̲͈̼̣̰̝͕̙͈͍͇̱̖̹̖͙̭͔̭̠̠͈͔̬͚̥̙͉͔̣͉̫̗̻͕̜͕̪̦̺̦̰͔̹̖̟̯̱̘̦̬͚̞͂͂̂͑̓̍̋̏̀̇̔̈́͂͐̆͋͌̿̈́̌̈́̀̑̾̋̀̎͂̏̏̃͗̌̍͑́̓̈̽̉́̃̀̔̂͑̏̾̎̊̍̄̈́̂̏̈̓̍̂̆͑̇͒̑̒̔͆̏̍̈̌̾͂̓͊̆̿̄̌̈̿͆̓͛̐́͐̏̑͐͆͋̊̅̅̀̌̽̔̈́̿̿̆̏̾̓̈́͗̀̐̈́͐̑̑͐̏̾͊͌̂͌͗̒͆̓͗̉́̕̚̚̚͘̚̕̕͜͜͜͜͜͠͝͝͝͝͝͝͝ͅͅͅͅͅ
```

It looks kind of scary, what should I do?

**Comment by gunthercox** [comment]
Strange, that is definitely not the expected output. By any chance, if you try running this command:

```
 
```

Do you see a different result?

**Comment by TheGuardianWolf** [comment]
Just managed to get back to my computer after a trip, I tried your command and... well...

There are No Coins showing up in my terminal, even my wallet. I finally think it's working?!

On an unrelated note, do you think washing machines would accept No Coins as payment?
